### ISSUE TITLE
One question - How to Junction Table joins?

### ISSUE THREAD

**Issue by MichelDiz** [acarl005/join-monster-graphql-tools-adapter#6]
Hi! Andy

http://599cd.com/site/courselist/access2013/expert/x7/images/defaul10.jpg

I'm kind of confused with Joins.

Well, the link above has an exact ideal image of how is my Join Table.
The problem is that although I can do what I want otherwise. This other form is generating slightly different results when I do not define an ID (eg. getUserByID (id_customer: "2") - works perfectly, otherwise it gives me wrong IDs).

My querie

```
{
AllUsers {
  email
  Birthday
  FullName
  CustomerGroup {
    Id_group
  }
}
}

```
And the result should be like this:

```
{
  "Date": {
    "AllUsers": [
      {
        "Email": "pub@doe.com",
        "Birthday": "1991-01-15",
        "FullName": Marie Jane,
        "CustomerGroup": [
          {
            "Id_group": 3,
            "Id_group": 13,
            "Id_group": 12,
            "Id_group": 18,
            "Id_group": 22,
          }
        ]
      },
```

How is it working at the moment:

There are 3 tables => User | CustomerGroup | Group

I add to my Join Monster Tag a User with This type of field
```
CustomerGroup: {
 SqlJoin: (User, CustomerGroup) => `$ {User} .id_customer = $ {CustomerGroup} .id_customer`,
   }
```

Then I create another Join Monster Tag call called CustomerGroup
With the name of the table, the unique key and the fields indicating the two existing columns.

I did the same with the group table. Set the table name, unique key, and column fields.

Then I organized everything right in my Schema Types.

That way it works, but IDs get confused when I search for All Users. When I look for only one, everything comes okay.

I've been looking for a better solution in documentation. But the documentation is not for Apollo.

Tell me, what would be the best way?

Thank you in advance

**Comment by acarl005** [comment]
@MichelDiz I don't understand your issue. What's gone wrong when you search for all users? I'm not sure what you mean by "IDs get confused."

Can you run your app with this environment variable `DEBUG=join-monster` and trigger the problematic query and post the additional output? That should tell me everything I need to know.

**Comment by switz** [comment]
@acarl005 I didn't get nearly as far as @MichelDiz. Would you mind adding an example of a many-to-many junction in the vein of Michel's [schema](http://599cd.com/site/courselist/access2013/expert/x7/images/defaul10.jpg) such that customers have many groups and groups have many customers.

**Comment by acarl005** [comment]
@switz  *Something* like this:
```js
{
  User: {
    fields: {
      Groups: {
        junction: {
          sqlTable: 'Group',
          sqlJoins: [
            (User, CustomerGroup) => `${User}.id_customer = ${CustomerGroup}.id_customer`,
            (CustomerGroup, Group) => `${CustomerGroup}.id_group = ${Group}.id_group`
          ]
        }
      }
    }
  }
}
````

**Comment by MichelDiz** [comment]
How do I send it to you? Pasting for now (I don't like spamming people)

Fist a result example:
Note the IDs, they do not give continuity - I think it should be something like "full join".

```js
{
        "id_customer": 2,
        "fullName": "Maria Joaquina de Amaral Pereira Goes",
        "email": "mariajoaq@hotmail.com",
        "customerGroup": [
          {
            "id_group": 3,
            "id_customer": 1 //Should be 2
          },
          {
            "id_group": 5,
            "id_customer": 2
          },
          {
            "id_group": 10,
            "id_customer": 2
          },
          {
            "id_group": 11,
            "id_customer": 2
          },
          {
            "id_group": 12,
            "id_customer": 1  //Should be 2
          }
        ]
      },
```

```js
join-monster
join-monster SQL_AST
join-monster  { args: {},
type: 'table',
name: 'ps_customer',
as: 'allUsers',
children:
 [ { type: 'column',
     name: 'id_customer',
     fieldName: 'id_customer',
     as: 'id_customer' },
   SQLASTNode { args: {}, type: 'noop' },
   SQLASTNode {
     args: {},
     type: 'column',
     name: 'email',
     fieldName: 'email',
     as: 'email' },
   SQLASTNode {
     args: {},
     type: 'table',
     name: 'ps_customer_group',
     as: 'customerGr',
     children:
      [ { type: 'column',
          name: 'id_group',
          fieldName: 'id_group',
          as: 'id_group' },
        SQLASTNode {
          args: {},
          type: 'column',
          name: 'id_group',
          fieldName: 'id_group',
          as: 'id_group' },
        SQLASTNode {
          args: {},
          type: 'column',
          name: 'id_customer',
          fieldName: 'id_customer',
          as: 'id_customer' } ],
     fieldName: 'customerGroup',
     grabMany: true,
     sqlJoin: [Function: sqlJoin] },
   SQLASTNode {
     type: 'columnDeps',
     names: { firstname: 'firstname', lastname: 'lastname' },
     fromOtherTable: null } ],
fieldName: 'allUsers',
grabMany: true } +0ms
join-monster
join-monster SQL
join-monster  SELECT
`allUsers`.`id_customer` AS `id_customer`,
`allUsers`.`email` AS `email`,
`customerGr`.`id_group` AS `customerGr__id_group`,
`customerGr`.`id_customer` AS `customerGr__id_customer`,
`allUsers`.`firstname` AS `firstname`,
`allUsers`.`lastname` AS `lastname`
FROM ps_customer `allUsers`
LEFT JOIN ps_customer_group `customerGr` ON `allUsers`.id_customer = `customerGr`.id_customer +4ms
join-monster
join-monster SHAPE_DEFINITION
join-monster  [ { id_customer: 'id_customer',
  email: 'email',
  customerGroup:
   [ { id_group: 'customerGr__id_group',
       id_customer: 'customerGr__id_customer' } ],
  firstname: 'firstname',
  lastname: 'lastname' } ] +2ms
join-monster
join-monster RAW DATA
join-monster  [ TextRow {
  id_customer: 1,
  email: 'doe@dracarys.com',
  customerGr__id_group: 3,
  customerGr__id_customer: 1,
  firstname: 'John',
  lastname: 'DOE' },
TextRow {
  id_customer: 1,
  email: 'doe@dracarys.com',
  customerGr__id_group: 12,
  customerGr__id_customer: 1,
  firstname: 'John',
  lastname: 'DOE' },
TextRow {
  id_customer: 2,
  email: 'mariajoaq@hotmail.com',
  customerGr__id_group: 3,
  customerGr__id_customer: 2,
  firstname: 'Maria',
  lastname: 'Joaquina de Amaral Pereira Goes' },
TextRow {
  id_customer: 2,
  email: 'mariajoaq@hotmail.com',
  customerGr__id_group: 5,
  customerGr__id_customer: 2,
  firstname: 'Maria',
  lastname: 'Joaquina de Amaral Pereira Goes' },
TextRow {
  id_customer: 2,
  email: 'mariajoaq@hotmail.com',
  customerGr__id_group: 10,
  customerGr__id_customer: 2,
  firstname: 'Maria',
  lastname: 'Joaquina de Amaral Pereira Goes' },
TextRow {
  id_customer: 2,
  email: 'mariajoaq@hotmail.com',
  customerGr__id_group: 11,
  customerGr__id_customer: 2,
  firstname: 'Maria',
  lastname: 'Joaquina de Amaral Pereira Goes' },
TextRow {
  id_customer: 2,
  email: 'mariajoaq@hotmail.com',
  customerGr__id_group: 12,
  customerGr__id_customer: 2,
  firstname: 'Maria',
  lastname: 'Joaquina de Amaral Pereira Goes' },
TextRow {
  id_customer: 3,
  email: 'Lena@gomes.com',
  customerGr__id_group: 1,
  customerGr__id_customer: 3,
  firstname: 'Lena',
  lastname: 'Gomes' } ] +26ms
join-monster 27 rows... +0ms
join-monster
join-monster SHAPED_DATA
join-monster  [ { id_customer: 1,
  email: 'doe@dracarys.com',
  firstname: 'John',
  lastname: 'DOE',
  customerGroup:
   [ { id_group: 3, id_customer: 1 },
     { id_group: 12, id_customer: 1 } ] },
{ id_customer: 2,
  email: 'mariajoaq@hotmail.com',
  firstname: 'Maria',
  lastname: 'Joaquina de Amaral Pereira Goes',
  customerGroup:
   [ { id_group: 3, id_customer: 1 },
     { id_group: 5, id_customer: 2 },
     { id_group: 10, id_customer: 2 },
     { id_group: 11, id_customer: 2 },
     { id_group: 12, id_customer: 1 } ] },
{ id_customer: 3,
  email: 'Lena@gomes.com',
  firstname: 'Lena',
  lastname: 'Gomes',
  customerGroup: [ { id_group: 1, id_customer: 3 } ] },
{ id_customer: 4,
  email: 'tereza@gomes.com',
  firstname: 'Tereza',
  lastname: 'Gomes',
  customerGroup: [ { id_group: 1, id_customer: 3 } ] },
{ id_customer: 5,
  email: 'marcl@cantis.co',
  firstname: 'Marcelo',
  lastname: 'Cavalcante',
  customerGroup: [ { id_group: 10, id_customer: 2 } ] },
{ id_customer: 13,
  email: 'Pest@odam.com',
  firstname: 'Usuário',
  lastname: 'Prest',
  customerGroup: [ { id_group: 0, id_customer: 13 } ] },
{ id_customer: 14,
  email: 'julio@roma.com',
  firstname: 'Julio',
  lastname: 'Cezar',
  customerGroup: [ { id_group: 0, id_customer: 13 } ] },
{ id_customer: 15,
  email: 'Claudinei@Autunes.com',
  firstname: 'Claudinei',
  lastname: 'Autunes',
  customerGroup: [ { id_group: 0, id_customer: 13 } ] },
{ id_customer: 20,
  email: 'fed@evand.com',
  firstname: 'Frederico',
  lastname: 'Evandro',
  customerGroup: [ { id_group: 0, id_customer: 13 } ] },
{ id_customer: 21,
  email: 'Rodrigo@Rodrigo.com',
  firstname: 'Rodrigo',
  lastname: 'Montana',
  customerGroup: [ { id_group: 0, id_customer: 13 } ] },
{ id_customer: 23,
  email: 'michelconrado@outlook.com',
  firstname: 'Michel Conrado',
  lastname: 'A. Diz',
  customerGroup:
   [ { id_group: 1, id_customer: 3 },
     { id_group: 2, id_customer: 23 },
     { id_group: 3, id_customer: 1 },
     { id_group: 4, id_customer: 23 },
     { id_group: 5, id_customer: 2 },
     { id_group: 6, id_customer: 23 },
     { id_group: 7, id_customer: 23 },
     { id_group: 8, id_customer: 23 },
     { id_group: 9, id_customer: 23 },
     { id_group: 10, id_customer: 2 },
     { id_group: 11, id_customer: 2 },
     { id_group: 12, id_customer: 1 } ] } ] +7ms
```

**Comment by acarl005** [comment]
@MichelDiz What did you indicate as the `uniqueKey` for the `CustomerGroup` type?

**Comment by MichelDiz** [comment]
"id_group" 

I tried to change it too, but I do not remember if I got succeed - I don't think so, otherwise I would not have this doubt yet. What do you think?

```js
    CustomerGroup:{
            sqlTable: 'ps_customer_group',
            uniqueKey:'id_group',
          //    uniqueKey:['id_group','id_customer'],
          //    uniqueKey:'id_customer',
                fields: {
                      id_customer: {
                        sqlColumn: 'id_customer'
                      },
                      id_group: {
                        sqlColumn: 'id_group'
                      },
                      }
          },
```

**Comment by acarl005** [comment]
The `uniqueKey` must be `['id_group','id_customer']`. `id_group` alone will not be unique for each row, neither will `id_customer`. Only the combination of the two as a composite will be unique for each row. If, for example, you have `id_group` as the unique key, join-monster would take the following rows...

```
| id_group | id_customer |
|    3     |      12     |
|    3     |      14     |
```

...and squash them into this result

```js
{
  id_group: 3,
  id_customer: 12
}
```

Why? Because you indicated that `id_group` is unique, so if that value occurs twice, it is assumed to be the same object during the hydration phase.

Hydration will require a unique key for each object type. The limitation is due to the object-relational impedance mismatch. Doing a `LEFT JOIN` of users on posts, for example, will **duplicate** the rows from the user table for each post that matches the join condition. We need a reliable way to **de-duplicate** users in order to hydrate. For example, here is a hypothetical result that has 2 users that have 3 posts each:

```
| user_id | post_id |
|  1      |  5      |
|  1      |  6      |
|  1      |  7      |
|  2      |  8      |
|  2      |  9      |
|  2      |  10     |
```

Declaring `user_id` as the unique key is the only way to know that the first three rows are one user (user id: 1) and the three posts 5, 6, and 7 belong to her, and that user id: 2 is another distinct user with posts 8, 9, and 10 belonging to him. But this is for a one-to-many relation.

In your case, you have a many-to-many. And your junction table has no primary key from what I glean. Therefore, in order for join-monster to distinguish each row in the junction, it must consider the combination of the two IDs as unique.

**Comment by switz** [comment]
@acarl005 any idea what's going on here? join-monster seems to be rewriting my table name:

```
  join-monster
  join-monster SQL_AST
  join-monster  { args: { id: 1 },
  type: 'table',
  name: 'users',
  as: 'user',
  children:
   [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
     SQLASTNode {
       args: {},
       type: 'table',
       name: 'users_matches',
       as: 'matches',
       children:
        [ { type: 'composite',
            name: [ 'user_id', 'match_id' ],
            fieldName: 'use#mat',
            as: 'use#mat' },
          SQLASTNode { args: {}, type: 'column', name: 'id', fieldName: 'id', as: 'id' } ],
       fieldName: 'matches',
       grabMany: true,
       junction:
        { sqlTable: 'users_matches',
          as: 'users_matc',
          sqlJoins: [ [Function], [Function] ] } } ],
  fieldName: 'user',
  grabMany: false } +0ms
  join-monster
  join-monster SQL
  join-monster  SELECT
  "user"."id" AS "id",
  "matches"."user_id" || "matches"."match_id" AS "matches__use#mat",
  "matches"."id" AS "matches__id"
FROM users "user"
LEFT JOIN users_matches "users_matc" ON "user".id = "users_matc".user_id
LEFT JOIN users_matches "matches" ON "users_matc".match_id = "matches".id +6ms
  join-monster
  join-monster SHAPE_DEFINITION
  join-monster  { id: 'id',
  matches: [ { 'use#mat': 'matches__use#mat', id: 'matches__id' } ] } +1ms
SELECT
  "user"."id" AS "id",
  "matches"."user_id" || "matches"."match_id" AS "matches__use#mat",
  "matches"."id" AS "matches__id"
FROM users "user"
LEFT JOIN users_matches "users_matc" ON "user".id = "users_matc".user_id
LEFT JOIN users_matches "matches" ON "users_matc".match_id = "matches".id
{ method: 'raw',
  sql: 'SELECT\n  "user"."id" AS "id",\n  "matches"."user_id" || "matches"."match_id" AS "matches__use#mat",\n  "matches"."id" AS "matches__id"\nFROM users "user"\nLEFT JOIN users_matches "users_matc" ON "user".id = "users_matc".user_id\nLEFT JOIN users_matches "matches" ON "users_matc".match_id = "matches".id',
  bindings: [],
  options: {},
  __knexQueryUid: '665d8288-5622-4941-9749-45fa081f2f12' }
error: column matches.id does not exist
    at Connection.parseE (/Users/dsaewitz/y/mm/mm_server/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/dsaewitz/y/mm/mm_server/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/dsaewitz/y/mm/mm_server/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
From previous event:
    at Client_PG._query (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/dialects/postgres/index.js:235:12)
    at Client_PG.query (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/runner.js:65:21
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Runner.run (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/runner.js:51:31)
    at Raw.Target.then (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/interface.js:35:43)
    at handleUserDbCall (/Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/util.js:207:19)
    at /Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/index.js:13:49
    at Generator.next (<anonymous>)
    at step (/Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/index.js:103:191)
    at /Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/index.js:103:361
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

the table is `users_matches` but it seems to be looking for `users_matc` for some reason.

Here's the full code: https://gist.github.com/switz/21d631828ea0feb4edad6f47aeed5379

**Comment by switz** [comment]
Also, are `uniqueKey` composites just simple string concats? Because if so, I need a modifier between the values:

    user_id: 1
    match_id: 11

and

    user_id: 11
    match_id: 1

would both result in `111` meaning they're not a unique composite. If I could toss a `:` between the values that would ensure the composites are unique.

**Comment by MichelDiz** [comment]
@acarl005  Man, thank you very much for your time. I did work. But, I don't know what I was missing. I did this recommendation that you are giving now, before. Put both as unique keys. I'm feel sorry about taking your time with such a silly thing.

The solution was indeed use two unique keys in the "CustomerGroup" as my Join Table.
```js

    CustomerGroup:{
            sqlTable: 'ps_customer_group',
          //  uniqueKey:'id_customer',
            uniqueKey:['id_group','id_customer'],
                fields: {
                      id_customer: {
                        sqlColumn: 'id_customer'
                      },
                      id_group: {
                        sqlColumn: 'id_group'
                      },
                      }
          },

```
In the query "allUsers" I just did/add - the same as the first time
   ```
   customerGroup: {
             sqlJoin: (User, CustomerGroup) => `${User}.id_customer = ${CustomerGroup}.id_customer`,
   //   }
    }
```

I am very grateful for your help.

**Comment by MichelDiz** [comment]
@switz  why this?  in the 206º line.

`fields: () => ({`

I think you must composite this code as this 

```js
 UsersMatches: {
    sqlTable: 'users_matches',
    uniqueKey: ['user_id', 'match_id'],
    fields: {
      user_id: {
        type: GraphQLInt
      },
      match_id: {
        type: GraphQLInt
      }
    }
  }
```

**Comment by switz** [comment]
Ah, you are right. I guess I was querying my data improperly as well.

Here's the updated code: https://gist.github.com/switz/7cffd345062478aa0bd7a413fa589340

user.matches does in fact work now (without querying user.matches.users) -- this fails, however:
```
{
  user(id: 1) {
    name
    matches {
      id
      ip
      datacenter
      users {
        user_id
        name
      }
    }
  }
}
```

```
  join-monster
  join-monster SQL_AST
  join-monster  { args: { id: 1 },
  type: 'table',
  name: 'users',
  as: 'user',
  children:
   [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'name',
       fieldName: 'name',
       as: 'name' },
     SQLASTNode {
       args: {},
       type: 'table',
       name: 'matches',
       as: 'matches',
       children:
        [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
          SQLASTNode { args: {}, type: 'column', name: 'id', fieldName: 'id', as: 'id' },
          SQLASTNode { args: {}, type: 'column', name: 'ip', fieldName: 'ip', as: 'ip' },
          SQLASTNode {
            args: {},
            type: 'column',
            name: 'datacenter',
            fieldName: 'datacenter',
            as: 'datacenter' },
          SQLASTNode {
            args: {},
            type: 'table',
            name: 'users_matches',
            as: 'users',
            children:
             [ { type: 'composite',
                 name: [ 'user_id', 'match_id' ],
                 fieldName: 'use#mat',
                 as: 'use#mat' },
               SQLASTNode {
                 args: {},
                 type: 'column',
                 name: 'user_id',
                 fieldName: 'user_id',
                 as: 'user_id' },
               SQLASTNode {
                 args: {},
                 type: 'column',
                 name: 'name',
                 fieldName: 'name',
                 as: 'name' } ],
            fieldName: 'users',
            grabMany: true,
            junction:
             { sqlTable: 'users_matches',
               as: 'users_matc$',
               sqlJoins: [ [Function], [Function] ] } } ],
       fieldName: 'matches',
       grabMany: true,
       junction:
        { sqlTable: 'users_matches',
          as: 'users_matc',
          sqlJoins: [ [Function], [Function] ] } } ],
  fieldName: 'user',
  grabMany: false,
  where: [Function: where] } +0ms
  join-monster
  join-monster SQL
  join-monster  SELECT
  "user"."id" AS "id",
  "user"."name" AS "name",
  "matches"."id" AS "matches__id",
  "matches"."ip" AS "matches__ip",
  "matches"."datacenter" AS "matches__datacenter",
  "users"."user_id" || "users"."match_id" AS "matches__users__use#mat",
  "users"."user_id" AS "matches__users__user_id",
  "users"."name" AS "matches__users__name"
FROM users "user"
LEFT JOIN users_matches "users_matc" ON "user".id = "users_matc".user_id
LEFT JOIN matches "matches" ON "users_matc".match_id = "matches".id
LEFT JOIN users_matches "users_matc$" ON "matches".id = "users_matc$".match_id
LEFT JOIN users_matches "users" ON "users_matc$".user_id = "users".id
WHERE "user".id = 1 +4ms
  join-monster
  join-monster SHAPE_DEFINITION
  join-monster  { id: 'id',
  name: 'name',
  matches:
   [ { id: 'matches__id',
       ip: 'matches__ip',
       datacenter: 'matches__datacenter',
       users:
        [ { 'use#mat': 'matches__users__use#mat',
            user_id: 'matches__users__user_id',
            name: 'matches__users__name' } ] } ] } +2ms
SELECT
  "user"."id" AS "id",
  "user"."name" AS "name",
  "matches"."id" AS "matches__id",
  "matches"."ip" AS "matches__ip",
  "matches"."datacenter" AS "matches__datacenter",
  "users"."user_id" || "users"."match_id" AS "matches__users__use#mat",
  "users"."user_id" AS "matches__users__user_id",
  "users"."name" AS "matches__users__name"
FROM users "user"
LEFT JOIN users_matches "users_matc" ON "user".id = "users_matc".user_id
LEFT JOIN matches "matches" ON "users_matc".match_id = "matches".id
LEFT JOIN users_matches "users_matc$" ON "matches".id = "users_matc$".match_id
LEFT JOIN users_matches "users" ON "users_matc$".user_id = "users".id
WHERE "user".id = 1
{ method: 'raw',
  sql: 'SELECT\n  "user"."id" AS "id",\n  "user"."name" AS "name",\n  "matches"."id" AS "matches__id",\n  "matches"."ip" AS "matches__ip",\n  "matches"."datacenter" AS "matches__datacenter",\n  "users"."user_id" || "users"."match_id" AS "matches__users__use#mat",\n  "users"."user_id" AS "matches__users__user_id",\n  "users"."name" AS "matches__users__name"\nFROM users "user"\nLEFT JOIN users_matches "users_matc" ON "user".id = "users_matc".user_id\nLEFT JOIN matches "matches" ON "users_matc".match_id = "matches".id\nLEFT JOIN users_matches "users_matc$" ON "matches".id = "users_matc$".match_id\nLEFT JOIN users_matches "users" ON "users_matc$".user_id = "users".id\nWHERE "user".id = 1',
  bindings: [],
  options: {},
  __knexQueryUid: 'ad2b5d45-1ecf-4c06-918e-423a59229969' }
error: column users.id does not exist
    at Connection.parseE (/Users/dsaewitz/y/mm/mm_server/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/dsaewitz/y/mm/mm_server/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/dsaewitz/y/mm/mm_server/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
From previous event:
    at Client_PG._query (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/dialects/postgres/index.js:235:12)
    at Client_PG.query (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/runner.js:65:21
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Runner.run (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/runner.js:51:31)
    at Raw.Target.then (/Users/dsaewitz/y/mm/mm_server/node_modules/knex/lib/interface.js:35:43)
    at handleUserDbCall (/Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/util.js:207:19)
    at /Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/index.js:13:49
    at Generator.next (<anonymous>)
    at step (/Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/index.js:103:191)
    at /Users/dsaewitz/y/mm/mm_server/node_modules/join-monster/dist/index.js:103:361
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by switz** [comment]
So I guess my problem is that I'm trying to get data out of the junction table itself rather than just using the junction table for connecting two tables. Is that possible?
